### ISSUE TITLE
styling the arrow?

### ISSUE THREAD

**Issue by jakubdonovan** [Brettm12345/svelte-tippy#310]
```css
:global(.tippy-arrow) {
	background: red;	
}
```
doesn't seem to do it. The box behind the arrow changes, but not the arrow itself.
